windowManager:
    mainWindow:
    firstWindow:

<mainWindow>:
    name: "main"
    fname:fname
    lname:lname

    GridLayout:
        cols: 2
        Label:
            text: "First Name:- "
        TextInput:
            id: fname
            multiline: False

        Label:
            text: "Last Name:- "
        TextInput:
            id: lname
            multiline: False

<firstWindow>:
    name: "first"
